#include "hal/board.h"

#include "config.h"
#include "stm32_hal.h"

using namespace teller::hal::board;

static reset_reason_t reasonOfLastReset = RESET_REASON_UNKNOWN;
static float temperature = 0.0f;
static float voltage = 0.0f;
static TIM_HandleTypeDef tickTimer;

static bool handleResetFlags(void);
static bool configureSystemClock(void);

#if defined(STM32H7)
#define RCC_FLAG_IWDGRST RCC_FLAG_IWDG1RST
#endif

namespace teller::hal::board {

bool init()
{
    return handleResetFlags() && configureSystemClock();
}

void destroy()
{
}

float getBoardTemperature()
{
    return temperature;
}

float getBoardVoltage()
{
    return voltage;
}

reset_reason_t getReasonOfLastReset(void)
{
    return reasonOfLastReset;
}

void updateBoardTemperature(float temperature_)
{
    temperature = temperature_;
}

void updateBoardVoltage(float voltage_)
{
    voltage = voltage_;
}

}

/**
 * @brief Updates the "reason of last reset" variable based on the RCC flags at boot.
 */
static bool handleResetFlags()
{
    if (__HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) {
        reasonOfLastReset = RESET_REASON_WATCHDOG;
    } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_SFTRST)) {
        reasonOfLastReset = RESET_REASON_SOFTWARE;
    } else {
        reasonOfLastReset = RESET_REASON_NORMAL;
    }

    __HAL_RCC_CLEAR_RESET_FLAGS();

    return true;
}

/**
 * @brief Configures the system clock.
 *
 * This function is a rough equivalent of the \c SystemClock_Config() function
 * generated by STM32CubeMX.
 */
static bool configureSystemClock()
{
    RCC_OscInitTypeDef oscInit = { 0 };
    RCC_ClkInitTypeDef clkInit = { 0 };

#if defined(STM32H7)
    /* Supply configuration update enable */
    HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
    while (!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) { };
#elif defined(STM32F4)
    /* Configure the main internal regulator output voltage */
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
#endif

    /* Configure the oscillators */
    oscInit.OscillatorType = RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSI | RCC_OSCILLATORTYPE_LSE | RCC_OSCILLATORTYPE_HSE;

    /* HSI: High Speed Internal oscillator (64 MHz @ STM32H7) */
#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.HSIState = RCC_HSI_DIV1;
#else
    oscInit.HSIState = RCC_HSI_ON;
#endif
    oscInit.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;

    /* LSI: Low Speed Internal oscillator (32 kHz @ STM32H7) */
    oscInit.LSIState = RCC_LSI_ON;

    /* LSE: Low Speed External oscillator (32.768 kHz @ STM32F4) */
#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.LSEState = RCC_LSE_OFF;
#else
    oscInit.LSEState = RCC_LSE_ON;
#endif

    /* HSE: High Speed External oscillator */
#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.HSEState = RCC_HSE_OFF;
#else
    oscInit.HSEState = RCC_HSE_ON;
#endif

    /* Phase-locked loop */
#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.PLL.PLLState = RCC_PLL_ON;
    oscInit.PLL.PLLSource = RCC_PLLSOURCE_HSI; /* HSI = 64 MHz */
    oscInit.PLL.PLLM = 4; /* 64 MHz / 4 = 16 MHz */
    oscInit.PLL.PLLN = 10; /* 16 MHz * 10 = 160 MHz */
    oscInit.PLL.PLLP = 2; /* Division factor for system clock --> 80 MHz, but the system clock runs from HSI */
    oscInit.PLL.PLLQ = 4; /* Division factor for peripheral clock --> 40 MHz */
    oscInit.PLL.PLLR = 2; /* Division factor for peripheral clock --> 80 MHz, unused */
    oscInit.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
    oscInit.PLL.PLLVCOSEL = RCC_PLL1VCOMEDIUM;
    oscInit.PLL.PLLFRACN = 0;
#else
    oscInit.PLL.PLLState = RCC_PLL_ON;
    oscInit.PLL.PLLSource = RCC_PLLSOURCE_HSE; /* HSE = 12 MHz */
    oscInit.PLL.PLLM = 6; /* 12 MHz / 6 = 2 MHz */
    oscInit.PLL.PLLN = 168; /* 2 MHz * 168 = 336 MHz */
    oscInit.PLL.PLLP = RCC_PLLP_DIV2; /* 336 / 2 = 168 MHz */
    oscInit.PLL.PLLQ = 7; /* 336 / 7 = 48 MHz */
#endif

    if (HAL_RCC_OscConfig(&oscInit) != HAL_OK) {
        return false;
    }

    /* Initializes the CPU, AHB and APB bus clocks */
    clkInit.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
        | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;

#if defined(TELLER_BOARD_NUCLEO144)
    /* System clock runs from HSI @ 64 MHz, requiring 1 wait cycle */
    clkInit.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
    clkInit.ClockType |= RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1;
    clkInit.SYSCLKDivider = RCC_SYSCLK_DIV1;
    clkInit.AHBCLKDivider = RCC_HCLK_DIV1;
    clkInit.APB1CLKDivider = RCC_APB1_DIV1;
    clkInit.APB2CLKDivider = RCC_APB2_DIV1;
    clkInit.APB3CLKDivider = RCC_APB3_DIV1;
    clkInit.APB4CLKDivider = RCC_APB4_DIV1;
    if (HAL_RCC_ClockConfig(&clkInit, FLASH_LATENCY_1) != HAL_OK) {
        return false;
    }
#else
    /* System clock runs from PLL @ 168 MHz, requiring 5 wait cycles */
    clkInit.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clkInit.AHBCLKDivider = RCC_HCLK_DIV1;
    clkInit.APB1CLKDivider = RCC_HCLK_DIV4;
    clkInit.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&clkInit, FLASH_LATENCY_5) != HAL_OK) {
        return false;
    }
#endif

    return true;
}

/* ************************************************************************** */
/* The functions below are required to set up TIM1 as the tick source in the  */
/* system instead of the built-in systick.
 */

extern "C" {

/**
 * @brief  This function configures the TIM1 as a time base source.
 *         The time source is configured  to have 1ms time base with a dedicated
 *         Tick interrupt priority.
 * @note   This function is called  automatically at the beginning of program after
 *         reset by HAL_Init() or at any time when clock is configured, by HAL_RCC_ClockConfig().
 * @param  TickPriority: Tick interrupt priority.
 * @retval HAL status
 */
HAL_StatusTypeDef HAL_InitTick(uint32_t TickPriority)
{
    RCC_ClkInitTypeDef clkconfig;
    uint32_t uwTimclock = 0U;

    uint32_t uwPrescalerValue = 0U;
    uint32_t pFLatency;
    HAL_StatusTypeDef status;

    /* Enable TIM1 clock */
    __HAL_RCC_TIM1_CLK_ENABLE();

    /* Get clock configuration */
    HAL_RCC_GetClockConfig(&clkconfig, &pFLatency);

    /* Compute TIM1 clock */
    uwTimclock = HAL_RCC_GetPCLK2Freq();

    /* Compute the prescaler value to have TIM1 counter clock equal to 1MHz */
    uwPrescalerValue = (uint32_t)((uwTimclock / 1000000U) - 1U);

    /* Initialize TIM1 */
    tickTimer.Instance = TIM1;

    /* Initialize TIMx peripheral as follows:
     *
     * Period = [(TIM1CLK/1000) - 1]. to have a (1/1000) s time base.
     * Prescaler = (uwTimclock/1000000 - 1) to have a 1MHz counter clock.
     * ClockDivision = 0
     * Counter direction = Up
     */
    tickTimer.Init.Period = (1000000U / 1000U) - 1U;
    tickTimer.Init.Prescaler = uwPrescalerValue;
    tickTimer.Init.ClockDivision = 0;
    tickTimer.Init.CounterMode = TIM_COUNTERMODE_UP;
    tickTimer.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

    status = HAL_TIM_Base_Init(&tickTimer);
    if (status == HAL_OK) {
        /* Start the TIM time Base generation in interrupt mode */
        status = HAL_TIM_Base_Start_IT(&tickTimer);
        if (status == HAL_OK) {
            /* Enable the TIM1 global Interrupt */
            HAL_NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
            /* Configure the SysTick IRQ priority */
            if (TickPriority < (1UL << __NVIC_PRIO_BITS)) {
                /* Configure the TIM IRQ priority */
                HAL_NVIC_SetPriority(TIM1_UP_TIM10_IRQn, TickPriority, 0U);
                uwTickPrio = TickPriority;
            } else {
                status = HAL_ERROR;
            }
        }
    }

    /* Return function status */
    return status;
}

/**
 * @brief  Suspend Tick increment.
 * @note   Disable the tick increment by disabling TIM1 update interrupt.
 * @param  None
 * @retval None
 */
void HAL_SuspendTick(void)
{
    /* Disable TIM1 update Interrupt */
    __HAL_TIM_DISABLE_IT(&tickTimer, TIM_IT_UPDATE);
}

/**
 * @brief  Resume Tick increment.
 * @note   Enable the tick increment by Enabling TIM1 update interrupt.
 * @param  None
 * @retval None
 */
void HAL_ResumeTick(void)
{
    /* Enable TIM1 Update interrupt */
    __HAL_TIM_ENABLE_IT(&tickTimer, TIM_IT_UPDATE);
}

void TIM1_UP_TIM10_IRQHandler(void)
{
    HAL_TIM_IRQHandler(&tickTimer);
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef* htim)
{
    if (htim->Instance == TIM1) {
        HAL_IncTick();
    }
}
}
