#include "hal/board.h"

#include "stm32_hal.h"

using namespace teller::hal::board;

static reset_reason_t reasonOfLastReset = RESET_REASON_UNKNOWN;

static bool handleResetFlags(void);
static bool configureSystemClock(void);

#if defined(STM32H7)
#define RCC_FLAG_IWDGRST RCC_FLAG_IWDG1RST
#endif

namespace teller::hal::board {

bool init()
{
    return handleResetFlags() && configureSystemClock();
}

void destroy()
{
}

float getBoardTemperature()
{
    return 0.0f;
}

float getBoardVoltage()
{
    return 0.0f;
}

reset_reason_t getReasonOfLastReset(void)
{
    return reasonOfLastReset;
}

}

/**
 * @brief Updates the "reason of last reset" variable based on the RCC flags at boot.
 */
static bool handleResetFlags()
{
    if (__HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) {
        reasonOfLastReset = RESET_REASON_WATCHDOG;
    } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_SFTRST)) {
        reasonOfLastReset = RESET_REASON_SOFTWARE;
    } else {
        reasonOfLastReset = RESET_REASON_NORMAL;
    }

    __HAL_RCC_CLEAR_RESET_FLAGS();

    return true;
}

/**
 * @brief Configures the system clock.
 *
 * This function is a rough equivalent of the \c SystemClock_Config() function
 * generated by STM32CubeMX.
 */
static bool configureSystemClock()
{
    RCC_OscInitTypeDef oscInit = { 0 };
    RCC_ClkInitTypeDef clkInit = { 0 };
    uint32_t flashLatency;

#if defined(STM32H7)
    /* Supply configuration update enable */
    // HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

    // __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);
    // while (!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) { };
#elif defined(STM32F4)
    /* Configure the main internal regulator output voltage */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
#endif

    /* Configure the oscillators */
    oscInit.OscillatorType = RCC_OSCILLATORTYPE_HSI | RCC_OSCILLATORTYPE_LSI;

    /* HSI: High Speed Internal oscillator (64 MHz @ STM32H7) */
#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.HSIState = RCC_HSI_DIV1;
#else
    oscInit.HSIState = RCC_HSI_ON;
#endif
    oscInit.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;

    /* LSI: Low Speed Internal oscillator (32 kHz @ STM32H7) */
    oscInit.LSIState = RCC_LSI_ON;

#if defined(TELLER_BOARD_NUCLEO144)
    oscInit.OscillatorType |= RCC_OSCILLATORTYPE_HSE;

    /* HSE: High Speed External oscillator */
    oscInit.HSEState = RCC_HSE_BYPASS;
#endif

#if defined(TELLER_BOARD_NUCLEO144)
    /* Phase-locked loop */
    oscInit.PLL.PLLState = RCC_PLL_ON;
    oscInit.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    oscInit.PLL.PLLM = 1;
    oscInit.PLL.PLLN = 24;
    oscInit.PLL.PLLP = 2; /* Division factor for system clock */
    oscInit.PLL.PLLQ = 4; /* Division factor for peripheral clock */
    oscInit.PLL.PLLR = 2; /* Division factor for peripheral clock */
    oscInit.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
    oscInit.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
    oscInit.PLL.PLLFRACN = 0;
#else
    oscInit.PLL.PLLState = RCC_PLL_NONE;
#endif

    if (HAL_RCC_OscConfig(&oscInit) != HAL_OK) {
        return false;
    }

    /* Initializes the CPU, AHB and APB bus clocks */
    clkInit.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
        | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clkInit.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
#if defined(TELLER_BOARD_NUCLEO144)
    clkInit.ClockType |= RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1;
    clkInit.SYSCLKDivider = RCC_SYSCLK_DIV1;
    clkInit.AHBCLKDivider = RCC_HCLK_DIV1;
    clkInit.APB1CLKDivider = RCC_APB1_DIV1;
    clkInit.APB2CLKDivider = RCC_APB2_DIV1;
    clkInit.APB3CLKDivider = RCC_APB3_DIV1;
    clkInit.APB4CLKDivider = RCC_APB4_DIV1;
#else
    clkInit.AHBCLKDivider = RCC_HCLK_DIV1;
    clkInit.APB1CLKDivider = RCC_HCLK_DIV1;
    clkInit.APB2CLKDivider = RCC_HCLK_DIV1;
#endif

    flashLatency = FLASH_LATENCY_0;
#if defined(TELLER_BOARD_NUCLEO144)
    flashLatency = FLASH_LATENCY_1;
#endif

    if (HAL_RCC_ClockConfig(&clkInit, flashLatency) != HAL_OK) {
        return false;
    }

    return true;
}

extern "C" {

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef* htim)
{
    if (htim->Instance == TIM1) {
        HAL_IncTick();
    }
}
}
