name: Run unit tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get install gcovr ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - uses: actions/cache@v4
        with:
          path: build/_deps
          key: v2-${{ runner.os }}-tests

      - name: Build and run tests
        run: |
          cmake . --preset test -B build
          cmake --build build
          ctest --test-dir build --output-junit report.xml

      - name: Build firmware
        run: |
          cmake . --preset default -B build-stm32
          cmake --build build-stm32

      - uses: test-summary/action@v2
        with:
          paths: "build/report.xml"

      - uses: actions/upload@v4
        with:
          name: firmware
          path: |
            build-stm32/teller-obc.bin
            build-stm32/teller-obc.elf
            build-stm32/teller-obc.hex
          if-no-files-found: error
