name: Run unit tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get install gcovr ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - uses: actions/cache@v4
        with:
          path: |
            build-prod/_deps
          key: v3-${{ runner.os }}-tests

      - name: Build and run tests
        run: |
          cmake . --preset host -B build -G Ninja
          cmake --build build
          ctest --timeout 5 --test-dir build --output-junit report.xml --output-on-failure

      - name: Build firmware
        run: |
          cmake . --preset default -B build-prod -G Ninja
          cmake --build build-prod

      - uses: test-summary/action@v2
        with:
          paths: "build/report.xml"

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build-prod/src/teller-obc.bin
            build-prod/src/teller-obc.elf
            build-prod/src/teller-obc.hex
          if-no-files-found: error
