name: Run unit tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get install gcovr ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - uses: actions/cache@v4
        with:
          path: build/_deps
          key: v2-${{ runner.os }}-tests

      - name: Build and run tests
        run: |
          cmake . --preset host -B build
          cmake --build build
          ctest --timeout 5 --test-dir build --output-junit report.xml --output-on-failure

      - name: Build firmware (dev board)
        run: |
          cmake . --preset devboard -B build-devboard
          cmake --build build-stm32

      - name: Build firmware (OBC board)
        run: |
          cmake . --preset default -B build-prod
          cmake --build build-stm32

      - uses: test-summary/action@v2
        with:
          paths: "build/report.xml"

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build-devboard/src/teller-obc.bin
            build-devboard/src/teller-obc.elf
            build-devboard/src/teller-obc.hex
            build-prod/src/teller-obc.bin
            build-prod/src/teller-obc.elf
            build-prod/src/teller-obc.hex
          if-no-files-found: error
